[WIP] Change audit strategy
pipermerriam/glados pull request #60
Opened 2023-02-11 08:37 UTC by perama-v

### Description

Updates the audit logic. This enables `glados-audit` to perform multiple
audity strategies within the one binary. 

Closes #38. 

### Overview

Note: Glados-monitor is unaffected. It continues to watch the chain tip of a non-portal node
and push content keys into the glados database. 

Multiple audit strategies are defined. Any (or all) may be invoked by spawning a new thread.
Each spawned thread sends audit tasks via a multi-producer single-consumer channel. Task-creating
threads do not alter the glados database.

An audit task is a content key from the the glados database that is expected to be in a portal node. Tasks are created according to different strategies:
- `latest` created (strategy that existed prior to this PR)
- `random`
- `missing`
- `<additional unimplemented strategies may be added later>`

A single thread watches the task channel and performs audits on anything received. Audit results
are stored in the glados database by this thread only, and no database locking is therefore required.

`glados-audit` may be started with a flag to control the audit strategy. 
- No flag: Use all strategies
- Flag: Use comma-delimited value strategies only.

### Changes

- New `generator` module to handle the different strategies.
- New `Strategy` enum 

### Checklist

- [x] Add thread spawner for different strategies
- [ ] Add CLI 
- [ ] Update latest with correct logic
- [ ] Implement missing
- [ ] Implement random
- [ ] Tidy commits

2023-02-14 19:18 UTC, mrferris requested changes
Looks good! 

Only thing I'd change are a few naming suggestions. The main one is that I think the name `selection.rs` describes what's being done here better than `generator.rs`. 

One suggestion for a future PR is that we include in the audit's DB record which selection strategy it was triggered by.

2023-02-14 19:18 UTC, mrferris commented on glados-audit/src/generator.rs
> +async fn generate_latest(tx: mpsc::Sender<HistoryContentKey>, conn: DatabaseConnection) -> ! {
```suggestion
async fn select_latest_content_for_audit(tx: mpsc::Sender<HistoryContentKey>, conn: DatabaseConnection) -> ! {
```

2023-02-14 19:18 UTC, mrferris commented on glados-audit/src/generator.rs
> +            debug!(err=?e, "Could not send header for audit, channel might be closed.")
The channel might also just be full, especially now that we're sending 30 queries per 120 seconds. 

This becomes a non-issue once we update Glados's `Client` library to run & wait on concurrent JSON RPC requests.

2023-02-14 19:18 UTC, mrferris commented on glados-audit/src/generator.rs
> +    /// Randomly generated content.
```suggestion
    /// Randomly selected content.
```

2023-02-14 23:50 UTC, perama-v commented on glados-audit/src/generator.rs
> +    Missing,
`Missing` is now `Failed`, and #62 tracks the new suggested strategies.

2023-02-14 23:51 UTC, perama-v commented on glados-audit/src/generator.rs
> +            debug!(err=?e, "Could not send header for audit, channel might be closed.")
Updated the error message to be "full or closed" for now

2023-02-15 00:00 UTC, perama-v commented
> One suggestion for a future PR is that we include within the audit's DB record which selection strategy it was triggered by.

See #63

2023-02-15 03:32 UTC, perama-v commented
All suggested changes have been made

2023-02-15 17:49 UTC, pipermerriam commented
can you rebase now that #59 is merged.

2023-02-15 22:14 UTC, perama-v commented
Rebased on `master`

2023-02-15 23:21 UTC, mrferris approved these changes

2023-02-16 00:48 UTC, pipermerriam commented
has conflicts now... probably from the other one I merged.

I'll get this merged and deployed tomorrow if the conflicts can get resolved by then.  Thanks again for all the great work.

2023-02-16 02:05 UTC, perama-v commented
Rebase on `main` done 👍

2023-02-23 06:28 UTC, perama-v commented
Testing of the `latest` strategy is now included.

2023-03-07 18:03 UTC, merged